repositories:
  - name: datadog
    url: https://helm.datadoghq.com
  - name: bitnamicharts
    url: https://charts.bitnami.com/bitnami
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: datadog-operator
    namespace: default
    chart: datadog/datadog-operator
  - name: rubygems-research-db
    namespace: rubygems-research-production
    chart: bitnamicharts/postgresql
    set:
      - name: auth.database
        value: rubygems_research_production
      - name: primary.persistence.size
        value: 1Ti
      - name: primary.resourcesPreset
        value: 2xlarge
      - name: postgresqlSharedPreloadLibraries
        value: pgaudit,pg_stat_statements
      - name: metrics.enabled
        value: true
      - name: primary.extendedConfiguration
        value: |
          pg_stat_statements.track = all
  - name: rubygems-db
    namespace: rubygems-research-production
    chart: bitnamicharts/postgresql
    set:
      - name: auth.database
        value: rubygems_production
      - name: primary.resourcesPreset
        value: xlarge
      - name: postgresqlSharedPreloadLibraries
        value: pgaudit,pg_stat_statements
      - name: metrics.enabled
        value: true
      - name: primary.extendedConfiguration
        value: |
          pg_stat_statements.track = all
  - name: cache
    namespace: rubygems-research-production
    chart: bitnamicharts/memcached
  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    set:
      - name: oauth.clientId
        value: kDMk3WXHL211CNTRL
