name: Docker
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    name: Docker build (and optional push)
    runs-on: ubuntu-22.04
    env:
      RUBYGEMS_VERSION: 3.5.10
      RUBY_VERSION: 3.3.1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-app
        uses: docker/metadata-action@b53be03109c4ef6f6cc7aa545b84b17a7fe51c1e
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push-app
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
        with:
          context: .
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          build-args: |
            APP_VERSION=${{ github.sha }}
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push-app.outputs.digest }}
          push-to-registry: true
