name: Docker
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    name: Docker build (and optional push)
    runs-on: ubuntu-22.04
    env:
      RUBYGEMS_VERSION: 3.5.10
      RUBY_VERSION: 3.3.1
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Log in to the Container registry
        uses: docker/login-action@7840e6ddd4a9223910798f6a315544257fccd96e
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-app
        uses: docker/metadata-action@2ee3d3070bb41b40bf7305d15233321e12c1dc5c
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push-app
        uses: docker/build-push-action@df19a799eba09c72273c5a94c70800e243e76ebc
        with:
          context: .
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          build-args: |
            APP_VERSION=${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push-app.outputs.digest }}
          push-to-registry: true
